package de.fuberlin.optimierung;

public enum LLVM_Operation {
	ALLOCA, STORE, LOAD, ADD, SUB, MUL, DIV, UDIV, SDIV, UREM, SREM,
	FADD, FSUB, FMUL, FDIV, FREM, SHL, LSHR, ASHR,
	BR, BR_CON, AND, OR, XOR, ICMP_EQ, ICMP_NE, ICMP_UGT, ICMP_UGE,
	ICMP_ULT, ICMP_ULE, ICMP_SGT, ICMP_SGE, ICMP_SLT, ICMP_SLE, RET,
	RET_CODE, COMMENT, CALL, GETELEMENTPTR, DUMMY, EXTRACTVALUE, INSERTVALUE
}